### ISSUE TITLE
Servers Not Responding

### ISSUE THREAD

**Issue by Hoully111** [BrianEstrada/PokeScanner#172] opened 2016-07-30 13:35 UTC
Servers Not Responding but ispokemongodowm sais everything is fine

**Comment by Hoully111** [comment] 2016-07-30 15:08
Went back to 1.7.3 works

**Comment by BrianEstrada** [comment] 2016-07-30 16:01
PTC or Google?

**Comment by Hoully111** [comment] 2016-07-30 16:11
Google

1.7.3 is working fine

**Comment by MarcQA** [comment] 2016-07-30 16:36
Can't log in using a Google account :(

**Comment by Hoully111** [comment] 2016-07-30 21:45
Any update

**Comment by BrianEstrada** [comment] 2016-07-30 22:36
Someday...eveenntuualllyyyyy I don't really like pushing updates without testing them so it might be a lil while.

**Comment by Hoully111** [comment] 2016-07-30 22:39
Fair enough just didn't know if the issue waa discovered

**Comment by BrianEstrada** [comment] 2016-07-30 22:43
ah yeah the issue is fixed in 1.7.5 It's finished I just neeeed some testing...feel like testing @Hoully111 ?

**Comment by Hoully111** [comment] 2016-07-30 22:44
Sure

**Comment by BrianEstrada** [comment] 2016-07-30 22:50
email me lovesguitar@gmail.com

**Comment by antibomb** [comment] 2016-07-31 02:29
stopped working entirely a little while ago.  upon taking the OTA auto-update to 1.7.5 its working much, much better.  just some additional evidence to what you likely already know.

**Comment by BrianEstrada** [comment] 2016-07-31 04:20
@antibomb thanks for the info

**Closed by BrianEstrada** 2016-07-31 04:20 UTC
