### ISSUE TITLE
Option to get navigation to the Pokemon location

### ISSUE THREAD

**Issue by Cynthiachecked** [BrianEstrada/PokeScanner#92] opened 2016-07-26 09:56 UTC
Hello, is there a possibility to add a navigation option in either this app or direct to google maps or something.

And I also want to use this issue question to thank you for your great work I am enjoying it to the fullest. Keep up!

**Comment by rhari991** [comment] 2016-07-26 09:58
This is in the pipeline, will be released in a day or two.
We are glad you are enjoying the app :)
Duplicate of #84

**Closed** 2016-07-26 09:59 UTC
Labels: duplicate
