### ISSUE TITLE
Highlight scanned areas within the circle on the map

### ISSUE THREAD

**Issue by robert862** [BrianEstrada/PokeScanner#76] opened 2016-07-25 08:38 UTC
It would be great if the parts of the circle, which have already been scanned would be highlighted.
That way the user knows whether there is no (non-filtered) Pin an area or that part of the circle has not been scanned yet.

**Comment by Sigi-cz** [comment] 2016-07-25 16:03
https://github.com/BrianEstrada/PokeScanner/issues/41

**Comment by EZTEQ** [comment] 2016-07-25 19:52
Closed as duplicate of #41

**Closed by EZTEQ** 2016-07-25 19:52 UTC
