### ISSUE TITLE
app crashes when resumed from task switch

### ISSUE THREAD

**Issue by someguy235** [BrianEstrada/PokeScanner#107] opened 2016-07-26 20:23 UTC
I'm getting consistent crashes ("Unfortunately PokeScanner has stopped") when switching back to this app after using other applications. It doesn't always happen, but I can reliably reproduce it by switching to a resource-intensive application (like Pokemon GO) and back. I wasn't seeing this until about a day ago. This is on a Nexus 5x.

**Comment by BrianEstrada** [comment] 2016-07-26 20:45
What version are you on?

**Comment by someguy235** [comment] 2016-07-26 20:49
1.6.5

**Comment by BrianEstrada** [comment] 2016-07-28 01:06
This should be fixed in 1.7.0 but is untested please let me know if the issue is fixed!

**Closed** 2016-07-28 01:06 UTC
